server:
  port: 8080
  servlet:
    context-path: /mymall
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mall?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
  redis:
    host: localhost
    database: 0
    port: 6379
    password:
    lettuce:
      pool:
        max-active: 8 # 连接池最大连接数（使用负值表示没有限制）
        max-wait: 1ms # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle:  8 # 连接池中的最大空闲连接
        min-idle:  0 # 连接池中的最小空闲连接
    timeout:  3000ms
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    virtual-host: /mall
    username: mall
    password: mall
    publisher-confirms: true
      # 自定义redis key
redisKey:
  prefix:
    authCode: "portal:authCode:"
  expire:
    authCode: 120 # 验证码超期时间
mybatis:
  mapper-locations:
    classpath: mapper/*.xml,com/wzf/mall/mapper/*.xml
jwt:
  secret: afan
  expiration: 120
  tokenHeader: Authorization
  tokenHead: Bearer

